name: Auto Tag and Release ğŸ¦§

on:
  push:
    branches: [main, master]

jobs:
  tag:
    name: Bumb Tag Version ğŸš€
    runs-on: ubuntu-latest
    outputs:
      newtag: ${{ steps.tag.outputs.new-tag }}
    steps:
      - name: Auto Tag
        uses: phish108/autotag-action@v1.1.64
        id: tag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
          branch: master
          bump: major
          release-branch: master
          dry-run: "true"

  releasse:
    name: Create GitHub Release ğŸ“°
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install git-cliff ğŸ”
        run: |
          export version=1.2.0
          wget "https://github.com/orhun/git-cliff/releases/download/v${version}/git-cliff-${version}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf git-cliff-*.tar.gz
          cp "git-cliff-${version}/git-cliff" /usr/local/bin/

      - name: Generate a changelog
        run: git-cliff -vv --latest --unreleased --strip header --config .github/workflows/configs/conf.toml --tag v${{needs.tag.outputs.newtag}} -o log.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cat Changelog
        run: cat log.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{needs.tag.outputs.newtag}}"
          release_name: "v${{needs.tag.outputs.newtag}}"
          body_path: log.md
 
