name: LaTex Cheks üïµ

on:
  pull_request:
    branches: [master, main]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changed-files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Looking for changed files üëÅ
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      changed_files_array: ${{ steps.format-changed-files.outputs.array_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**.tex"
          separator: ','
      - run: echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Format changed files
        id: format-changed-files
        run: |
          files="${{ steps.changed-files.outputs.all_changed_files }}"
          IFS=',' read -r -a file_array <<< "$files"
          echo "array_changed=$file_array" >> "$GITHUB_OUTPUT"

  linter:
    needs: changed-files
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Linter Checker üñä
    if: needs.changed-files.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Chktex
        run: sudo apt-get install chktex -y

      - name: Run Chktex
        id: chktex
        run: chktex ${{ needs.changed-files.outputs.all_changed_files }}

  styler:
    needs: changed-files
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Styler Checker ‚ú®
    if: needs.changed-files.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Java ‚òïÔ∏è
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Install textidote
        run: wget https://github.com/sylvainhalle/textidote/releases/latest/download/textidote.jar

      - name: Run textidote
        run: |
           file_array="${{ needs.changed-files.outputs.changed_files_array }}"
        
           for file in "${file_array[@]}"; do
              java -jar textidote.jar "$file"
            done

  typo:
    needs: changed-files
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Typo Checker üîç
    if: needs.changed-files.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Java ‚òïÔ∏è
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Install ltex-cli
        run: wget https://github.com/valentjn/ltex-ls/releases/latest/download/ltex-ls-16.0.0.tar.gz && tar xvf ltex-ls-16.0.0.tar.gz

      - name: Run ltex-cli
        run: |
          changed_files="${{ needs.changed-files.outputs.all_changed_files }}"
          IFS=',' read -r -a file_array <<< "$changed_files"
     
          errors_found=0

          for file in "${file_array[@]}"; do
            echo "Checking file: $file"
            ./ltex-ls-16.0.0/bin/ltex-cli --client-configuration=.github/workflows/configs/ltex.json "$file"
            exit_code=$?
            
            if [ $exit_code -ne 0 ]; then
              echo "Error found in file: $file (exit code: $exit_code)"
              errors_found=1
            fi
          done
          
          if [ $errors_found -eq 1 ]; then
            echo "Errors were found in one or more files"
            exit 1
          fi
