name: Todo Comments ðŸ”«
on: [pull_request]

jobs:
  todo-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Todo Comments âœ…
        uses: gkampitakis/github-action-todo-commenter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-pattern: '.yml'
          review-message: "monello ðŸ‘¹, hai aggiunto dei TODO che vanno sistemati !"
          # optional, default is "TODO:,FIXME:,BUG:"
          tags: "TODO:,FIXME:,BUG:"
